package util;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
Author: Braeden Palomino
Date: 11/14/24
Description: Util class that serves as notification panel for messages. 
 */
public class MessageBox extends javax.swing.JDialog {

    private static JFrame mainFrame;

    ImageIcon iconError = new ImageIcon(getClass().getClassLoader().getResource("icons/error-alert.png"));
    ImageIcon iconCheck = new ImageIcon(getClass().getClassLoader().getResource("icons/check-alert.png"));
    ImageIcon iconHelp = new ImageIcon(getClass().getClassLoader().getResource("icons/help-alert.png"));

    public static final int ERROR = 1;
    public static final int SUCCESS = 2;
    public static final int INFO = 3;

    /**
     * Creates new form MessageBox
     */
    public MessageBox(boolean modal, String message, int alertType) {
        super(mainFrame, modal);
        initComponents();
        setLocationRelativeTo(mainFrame);

        setUp(this, alertType, message);
    }

    public MessageBox(boolean modal, int alertType) {
        super(mainFrame, modal);
        initComponents();
        setLocationRelativeTo(mainFrame);

        String message = "Welcome to the BeatBoxPOS (Point of Sales) Software\n\n"
                + "Logon Page:\n"
                + "Logon using your username (Not case sensitive) and password (Case sensitive)."
                + "\n\n---------------------------------------------------------------------------\n\n"
                + "Password Reset Pages:\n"
                + "1. Go to \"Login\" Page and select \"forgot password\"\n"
                + "2. Enter the username for the account you forgot the password to. (Not case sensitive)\n"
                + "3. Answer all 3 security questions correctly. (Not case sensitive)\n"
                + "4. Create a new password. It must be 8-20 characters and have 3 options completed.\n"
                + "- (Required) Must be between 8-20 characters\n"
                + "- (Option) Must have uppercase character\n"
                + "- (Option) Must have lowercase character\n"
                + "- (Option) Must have digit character\n"
                + "- (Option) Must have special character ()!@#$%^&*\n"
                + "\n\n---------------------------------------------------------------------------\n\n"
                + "Create Account Page:\n"
                + "Fill out the form, make sure all red fields marked with * are completed.\n"
                + "Required Fields:\n"
                + "- Username\n"
                + "- Password\n"
                + "- Security Question Answers 1-3\n"
                + "- First & Last Name\n"
                + "- Address title\n"
                + "- City\n"
                + "- State\n"
                + "- Zipcode\n";

        setUp(this, alertType, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        icon = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextPane();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IMPORTANT MESSAGE");
        setIconImage(null);
        setSize(new java.awt.Dimension(200, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        icon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(icon, gridBagConstraints);

        panelInfo.setLayout(new java.awt.BorderLayout());

        scrollPane.setBorder(null);

        textArea.setEditable(false);
        textArea.setBorder(null);
        textArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textArea.setText("This is where the text for the message box will go. Things like errors and other things will be here.");
        textArea.setMinimumSize(new java.awt.Dimension(100, 100));
        scrollPane.setViewportView(textArea);

        panelInfo.add(scrollPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(panelInfo, gridBagConstraints);

        btnClose.setBackground(new java.awt.Color(0, 153, 153));
        btnClose.setText("Close");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void setUp(JDialog box, int alertType, String message) {
        // Set text styles and box dimensions
        StyledDocument doc = textArea.getStyledDocument();
        SimpleAttributeSet style = new SimpleAttributeSet();

        StyleConstants.setLineSpacing(style, (float) .5);

        switch (alertType) {
            case ERROR:
                icon.setIcon(iconError);
                setTitle("ERROR");
                StyleConstants.setAlignment(style, StyleConstants.ALIGN_CENTER);
                box.setSize(350, 250);
                break;
            case SUCCESS:
                icon.setIcon(iconCheck);
                setTitle("SUCCESS");
                StyleConstants.setAlignment(style, StyleConstants.ALIGN_CENTER);
                box.setSize(350, 250);
                break;
            case INFO:
                icon.setIcon(iconHelp);
                setTitle("INFORMATION");
                StyleConstants.setAlignment(style, StyleConstants.ALIGN_LEFT);
                box.setSize(700, 500);
                break;
        }

        doc.setParagraphAttributes(0, doc.getLength(), style, false);

        textArea.setText(message);
        setVisible(true);

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                (scrollPane.getVerticalScrollBar()).setValue(0);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextPane textArea;
    // End of variables declaration//GEN-END:variables
}
