package views;

import views.logon.PanelLogon;
import util.StateManager;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Component;
import util.ImageManager;
import util.ResourceLoader;
import views.customer.PanelCustomer;
import views.logon.PanelCreateAccount;

/*
Author: Braeden Palomino
Date: 10/08/24
Description: The main frame / main class for the entire program. Contains a toolbar with key functions as well as a mainPanel which is changed
using StateManager depending on the state or actions the user takes.

final push - Customer View Status Check (2024-11-15)
 */
public class FrameMain extends javax.swing.JFrame {

    private StateManager panelState;

    public FrameMain() {
        initComponents();

        panelState = new StateManager(this, mainPanel);
        panelState.changePanel(new PanelLogon(panelState));

        setTitle("BeatBox POS - Login");
        setSize(1250, 750);
        setLocationRelativeTo(null);
        setIconImage(ResourceLoader.getResourceIcon("icons/smallLogo.png", ImageManager.SIZE_ICON).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        panelToolbars = new javax.swing.JPanel();
        toolbarLogon = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        toolbarActive = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BeatBox POS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        toolbar.setFloatable(false);
        toolbar.setRollover(true);
        toolbar.setMargin(new java.awt.Insets(3, 3, 3, 3));

        panelToolbars.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        toolbarLogon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        toolbarLogon.add(btnLogin);

        btnCreate.setText("Create New Account");
        btnCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        toolbarLogon.add(btnCreate);

        btnBrowse.setText("Browse as Guest");
        btnBrowse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrowse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsedClicked(evt);
            }
        });
        toolbarLogon.add(btnBrowse);

        panelToolbars.add(toolbarLogon);

        toolbarActive.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnLogout.setText("Logout");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        toolbarActive.add(btnLogout);

        panelToolbars.add(toolbarActive);
        toolbarActive.setVisible(false);

        btnHelp.setText("Help");
        btnHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        panelToolbars.add(btnHelp);

        toolbar.add(panelToolbars);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:  
        Thread testThread = new Thread(new Runnable() {
            @Override
            public void run() {
            }
        });
        testThread.start();

    }//GEN-LAST:event_formWindowOpened

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:

        panelState.showHelp();
        btnHelp.setEnabled(false);
        
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnBrowsedClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsedClicked
        // TODO add your handling code here:
        panelState.changePanel(new PanelCustomer(panelState));

        repaint();
        revalidate();
    }//GEN-LAST:event_btnBrowsedClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        panelState.changePanel(new PanelCreateAccount(panelState));

        repaint();
        revalidate();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        panelState.changePanel(new PanelLogon(panelState));

        repaint();
        revalidate();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        panelState.setCurrentUser(null, null);
        panelState.changePanel(new PanelLogon(panelState));

        switchToolBar("Logon");
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);

            }
        });
    }

    public void switchToolBar(String bar) {

        for (Component c : panelToolbars.getComponents()) {
            c.setVisible(false);
        }

        btnHelp.setEnabled(true);
        
        switch (bar) {
            case "Manager":
                toolbarActive.setVisible(true);
                break;
            case "Employee":
                toolbarActive.setVisible(true);
                break;
            case "Customer":
                toolbarActive.setVisible(true);
                break;
            case "Help":
            case "Logon":
                toolbarLogon.setVisible(true);
        }

        btnHelp.setVisible(true);

        revalidate();
        repaint();

    }

    public void requestFocus() {
        btnHelp.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelToolbars;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JPanel toolbarActive;
    private javax.swing.JPanel toolbarLogon;
    // End of variables declaration//GEN-END:variables
}
