package views.manager.users;

import util.StateManager;
import views.logon.PanelCreateAccount;

public class PanelUsers extends javax.swing.JPanel {

    private StateManager panelState;

    private PanelUsersManage panelUsersManage;
    private PanelCreateAccount panelCreateUsers;

    public PanelUsers(StateManager panelState) {
        this.panelState = panelState;
        this.panelCreateUsers = new PanelCreateAccount(panelState);
        this.panelUsersManage = new PanelUsersManage(panelState);
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        tabbedPane.setBackground(new java.awt.Color(0, 153, 153));
        tabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPane.setName("Manager"); // NOI18N
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });
        add(tabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        // TODO add your handling code here:
        try {
            panelUsersManage.populateTable();
        } catch (Exception x) {
        }

    }//GEN-LAST:event_tabbedPaneStateChanged

    private void setup() {
        tabbedPane.add("Manage Users", panelUsersManage);
        tabbedPane.add("Create Users", panelCreateUsers);
    }

    public void fireTabbedPane() {
        panelUsersManage.populateTable();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
